# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='', verbose_name='Document Upload')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title (English)')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description (English)')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='Type')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.Project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Employee', verbose_name='Updated By')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='projects.Employee', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('original_document', models.BooleanField(default=False, help_text='Are you actually moving the original document or just a copy?', verbose_name='Original Document?')),
                ('handing_party_role', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('ARCHIVE', 'Archive'), ('EMPLOYEE', 'Employee')], max_length=20, null=True, verbose_name='Handing Party Role')),
                ('receiving_party_role', models.CharField(choices=[('CLIENT', 'Client'), ('ARCHIVE', 'Archive'), ('EMPLOYEE', 'Employee')], max_length=20, null=True, verbose_name='Receiving Party Role')),
                ('movement_date', models.DateTimeField(null=True, verbose_name='Movement Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='archive.Document', verbose_name='Document')),
                ('handing_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_documents', to='projects.Person', verbose_name='Handing Party')),
                ('receiving_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='projects.Person', verbose_name='Receiving Party')),
            ],
            options={
                'verbose_name': 'Document Movement',
                'verbose_name_plural': 'Document Movements',
                'ordering': ['-movement_date'],
            },
        ),
    ]
