# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentmovement',
            options={'verbose_name': 'Document Movement', 'verbose_name_plural': 'Document Movements'},
        ),
    ]
