# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
    ]
