# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20171114_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmovement',
            name='hard_copy',
        ),
        migrations.AddField(
            model_name='documentmovement',
            name='original_document',
            field=models.BooleanField(default=False, verbose_name='Original Document?'),
        ),
    ]
