# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20171127_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='description_ar',
        ),
    ]
