# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20171130_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmovement',
            options={'ordering': ['-movement_date'], 'verbose_name': 'Document Movement', 'verbose_name_plural': 'Document Movements'},
        ),
        migrations.AlterField(
            model_name='documentmovement',
            name='original_document',
            field=models.BooleanField(default=False, help_text='Are you actually moving the original document or just a copy?', verbose_name='Original Document?'),
        ),
    ]
