# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20171201_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='documentmovement',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='archive.Document', verbose_name='Document'),
        ),
    ]
