# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title (English)')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description (English)')),
                ('type', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Type')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_copy', models.BooleanField(default=False, verbose_name='Show')),
                ('handing_party_role', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('ARCHIVE', 'Archive'), ('EMPLOYEE', 'Employee')], max_length=20, null=True, verbose_name='Handing Party Role')),
                ('receiving_party_role', models.CharField(choices=[('CLIENT', 'Client'), ('ARCHIVE', 'Archive'), ('EMPLOYEE', 'Employee')], max_length=20, null=True, verbose_name='Receiving Party Role')),
                ('handing_date', models.DateTimeField(null=True, verbose_name='Handing Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='projects.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(db_index=True, max_length=30, null=True)),
                ('lookup_value_ar', models.CharField(max_length=100, null=True)),
                ('lookup_value_en', models.CharField(max_length=100, null=True)),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(null=True, verbose_name='Display Order')),
            ],
            options={
                'verbose_name_plural': 'Look ups',
                'ordering': ['lookup_type', '-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_ar', models.CharField(max_length=100, null=True, verbose_name='Nationality (Arabic)')),
                ('nationality_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality (English)')),
                ('country_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality (Arabic)')),
                ('country_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality (Arabic)')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(null=True, verbose_name='Display Order')),
            ],
            options={
                'verbose_name_plural': 'Admission: Nationalities',
                'ordering': ['display_order', 'nationality_en'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Organization Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Organization Name (English)')),
                ('type', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Type')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('address', models.TextField(null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Full Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Full Name (English)')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='Mobile')),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Home Phone')),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Work Phone')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Personal Email')),
                ('government_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Government ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title (English)')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description (English)')),
                ('fees', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Project')),
                ('case_reference', models.CharField(max_length=100, null=True, verbose_name='Case Reference')),
                ('type', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Type')),
                ('client_role', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Client Role')),
                ('opponent_role', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Opponent Role')),
            ],
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Person')),
            ],
            bases=('projects.person',),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Project')),
                ('type', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Type')),
            ],
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Organization')),
            ],
            bases=('projects.organization',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Person')),
                ('job_description_ar', models.CharField(max_length=255, null=True, verbose_name='Job Description')),
                ('job_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Description (English)')),
                ('joining_date', models.DateTimeField(null=True, verbose_name='Joining Date')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='Qualifications')),
                ('monthly_salary', models.FloatField(blank=True, null=True, verbose_name='Monthly Salary')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('projects.person',),
        ),
        migrations.CreateModel(
            name='Paperwork',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Project')),
                ('type', models.CharField(choices=[('--', '--')], max_length=100, null=True, verbose_name='Type')),
            ],
            bases=('projects.project',),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Nationality'),
        ),
        migrations.AddField(
            model_name='documentmovement',
            name='handing_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_documents', to='projects.Person', verbose_name='Handing Party'),
        ),
        migrations.AddField(
            model_name='documentmovement',
            name='receiving_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='projects.Person', verbose_name='Receiving Party'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_project', to='projects.Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_project_created_projects', to='projects.Employee', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects_project', to='projects.Employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Employee', verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Employee', verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='projects.Employee', verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_persons', to='projects.Organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposing_cases', to='projects.Court'),
        ),
        migrations.AddField(
            model_name='case',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposing_cases', to='projects.Client'),
        ),
    ]
