# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_persons', to='projects.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The user associated with this employee holds the credentials data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_type',
            field=models.CharField(choices=[('ORGANIZATION_TYPE', 'Organization Type'), ('CASE_TYPE', 'Case Type'), ('CONSULTATION_TYPE', 'Consultation Type'), ('PAPERWORK_TYPE', 'Paperwork Type'), ('DOCUMENT_TYPE', 'Document Type'), ('COURT_TYPE', 'Court Type'), ('COURT_ROLE', 'Court Role')], db_index=True, max_length=30, null=True, verbose_name='Lookup Type'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='country_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country (Arabic)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='country_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country (English)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='projects.Project', verbose_name='Project'),
        ),
    ]
