# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='case',
            name='client_role',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Client Role'),
        ),
        migrations.AlterField(
            model_name='case',
            name='opponent_role',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Opponent Role'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='type',
            field=models.CharField(choices=[('', '---------')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
