# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180121_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Case Reference'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Name (English)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fees',
            field=models.CharField(max_length=200, null=True, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='summary_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
    ]
