# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180725_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (English)'),
        ),
    ]
