# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171106_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmovement',
            name='handing_date',
        ),
        migrations.AddField(
            model_name='case',
            name='court_office',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Court Office'),
        ),
        migrations.AddField(
            model_name='documentmovement',
            name='movement_date',
            field=models.DateTimeField(null=True, verbose_name='Movement Date'),
        ),
    ]
