# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171109_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='documentmovement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentmovement',
            name='handing_party',
        ),
        migrations.RemoveField(
            model_name='documentmovement',
            name='receiving_party',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentMovement',
        ),
    ]
