# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20171114_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title (English)')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description (English)')),
                ('date', models.DateTimeField(null=True, verbose_name='Reminder Date')),
                ('type', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('BOTH', 'Both')], max_length=10, null=True, verbose_name='Type')),
                ('last_seen_on', models.DateTimeField(null=True, verbose_name='Last Seen On')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='projects.Project')),
                ('whom_to_remind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='projects.Employee', verbose_name='Whom To Remind')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
            },
        ),
    ]
