# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Status Comments'),
        ),
    ]
