# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20171119_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('summary_en', models.CharField(max_length=100, null=True, verbose_name='Title (English)')),
                ('details_ar', models.TextField(null=True, verbose_name='Description')),
                ('details_en', models.TextField(null=True, verbose_name='Description (English)')),
                ('date', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('inform_the_client', models.BooleanField(default=True, verbose_name='Inform The Client')),
                ('created_on', models.DateTimeField(null=True, verbose_name='Created On')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='projects.Employee', verbose_name='Creator')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Updates',
                'verbose_name': 'Update',
            },
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.AddField(
            model_name='person',
            name='personal_picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Personal Picture'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('', '---------'), ('قانونية', 'قانونية')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='type',
            field=models.CharField(choices=[('', '---------'), ('تجديد رخصة محل', 'تجديد رخصة محل')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
