# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20171125_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ('-date',), 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ('-date',), 'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AddField(
            model_name='update',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attachments'),
        ),
    ]
