# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 10:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171127_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Monthly Salary'),
        ),
    ]
