# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171130_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated_on', 'created_on'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_ar',
        ),
    ]
