# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20171201_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposing_cases', to='projects.Court', verbose_name='Court'),
        ),
        migrations.AlterField(
            model_name='case',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposing_cases', to='projects.Client', verbose_name='Opponent'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('', '---------'), ('محمكة', 'محمكة'), ('مؤسسة', 'مؤسسة')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='type',
            field=models.CharField(choices=[('', '---------'), ('تأسيس شركة', 'تأسيس شركة'), ('تجديد رخصة محل', 'تجديد رخصة محل')], max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_project', to='projects.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects_project', to='projects.Employee', verbose_name='Main Assignee'),
        ),
    ]
