# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 10:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Amount')),
                ('justification', models.CharField(max_length=255, null=True, verbose_name='Justification')),
                ('justification_proof', models.FileField(blank=True, null=True, upload_to='', verbose_name='Justification Proof')),
                ('request_date', models.DateTimeField(null=True, verbose_name='Request Date')),
                ('approval_status', django_fsm.FSMField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=50, verbose_name='Approval Status')),
                ('approved_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3)),
                ('approved_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Approved Amount')),
                ('approval_comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Approval Comments')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_funds', to='projects.Employee', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fund_requests', to='projects.Employee', verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_funds', to='projects.Project')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_funds', to='projects.Employee', verbose_name='Requester')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Employee', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Fund Request',
                'verbose_name_plural': 'Fund Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25, null=True, verbose_name='Invoice Reference')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Amount')),
                ('date', models.DateTimeField(null=True, verbose_name='Invoice Date')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.Client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to='projects.Employee', verbose_name='Created By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.Project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Employee', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title (English)')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Amount')),
                ('description_ar', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Description (English)')),
                ('handing_party_role', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('ACCOUNTING', 'Accounting'), ('EMPLOYEE', 'Employee')], max_length=20, null=True, verbose_name='Handing Party Role')),
                ('receiving_party_role', models.CharField(choices=[('CLIENT', 'Client'), ('ACCOUNTING', 'Accounting'), ('EMPLOYEE', 'Employee')], max_length=20, null=True, verbose_name='Receiving Party Role')),
                ('transaction_date', models.DateTimeField(null=True, verbose_name='Transaction Date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to='projects.Employee', verbose_name='Created By')),
                ('fund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.FundRequest')),
                ('handing_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_payments', to='projects.Person', verbose_name='Handing Party')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.Invoice')),
                ('receiving_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='projects.Person', verbose_name='Receiving Party')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Employee', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
