# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171109_0943'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequests',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_funds', to='projects.Project'),
        ),
    ]
