# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 14:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fundrequests_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequests',
            name='approval_comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Approval Comments'),
        ),
        migrations.AlterField(
            model_name='fundrequests',
            name='approved_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Approved Amount'),
        ),
    ]
