# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20171114_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundRequests',
            new_name='FundRequest',
        ),
        migrations.AlterModelOptions(
            name='fundrequest',
            options={'verbose_name': 'Fund Request', 'verbose_name_plural': 'Fund Requests'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Invoice Reference'),
        ),
    ]
