# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 07:01
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20171116_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='approval_status',
            field=django_fsm.FSMField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=50, verbose_name='Approval Status'),
        ),
    ]
