# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 11:56
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20171127_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', max_digits=11, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('SAR', 'SAR'), ('USD', 'USD $')], default='SAR', editable=False, max_length=3),
        ),
    ]
