# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171127_1332'),
        ('accounting', '0008_auto_20171128_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
