# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_invoice_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Fund Request', 'verbose_name_plural': 'Fund Requests'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.Client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(max_length=25, null=True, verbose_name='Invoice Reference'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
    ]
